import Link from "next/link";
import { getSupabaseServer } from "../lib/supabase-server";
export default async function Home(){
 const s=await getSupabaseServer(); const {data:{user}}=await s.auth.getUser(); let role="";
 if(user){const {data:p}=await s.from("profiles").select("role").eq("id",user.id).maybeSingle(); role=p?.role||""}
 const dashboard=role==="admin"?"/admin":role==="campaign_owner"?"/owner":"/dashboard";
 return <main>
  <section className="wrap hero home-hero"><div className="eyebrow">CREATOR × BRAND MARKETPLACE</div><h1>Platform clipping yang punya ruang khusus untuk Creator dan Brand.</h1><p className="hero-copy">Creator fokus cari campaign dan menghasilkan clip. Brand fokus membuat campaign, mengatur budget, dan memantau performa. Satu platform, dua pengalaman yang berbeda.</p><div className="hero-actions">{user?<Link className="btn" href={dashboard}>{role==="campaign_owner"?"Masuk Brand Studio":"Buka Dashboard"}</Link>:<><Link className="btn" href="/campaigns">Cari Campaign</Link><Link className="btn secondary" href="/register">Daftar</Link></>}</div></section>
  <section className="wrap portal-grid">
   <div className="portal-card creator-portal"><div className="eyebrow">UNTUK CREATOR</div><h2>Temukan campaign. Buat clip. Dapat reward.</h2><p className="muted">Lihat brief, cek rate per 1.000 views, submit link TikTok/Instagram/YouTube, dan pantau hasil review.</p><div className="portal-points"><span>Campaign Marketplace</span><span>Submission Tracking</span><span>Wallet & Payout</span></div><Link className="btn" href="/campaigns">Lihat Campaign →</Link></div>
   <div className="portal-card brand-portal"><div className="eyebrow">UNTUK BRAND</div><h2>Bangun campaign dan scale distribusi lewat creator.</h2><p className="muted">Buat campaign, tentukan reward dan budget, top up saldo campaign, lalu kelola campaign dari Brand Studio.</p><div className="portal-points"><span>Campaign Builder</span><span>Budget & Wallet</span><span>Submission Review</span></div><Link className="btn brand-btn" href={user&&role==="campaign_owner"?"/owner":"/register"}>{user&&role==="campaign_owner"?"Masuk Brand Studio":"Mulai sebagai Brand →"}</Link></div>
  </section>
  <section className="wrap section"><div className="section-head"><div><div className="eyebrow">HOW IT WORKS</div><h2>Alurnya dibuat jelas dari awal.</h2></div></div><div className="grid">{[["01","Brand membuat campaign","Atur brief, platform, rate, rules, dan budget. Campaign masuk review admin sebelum tayang."],["02","Creator memilih campaign","Creator melihat campaign aktif dan mengerjakan konten sesuai brief."],["03","Submit & review","Link clip dikirim untuk direview. Views yang disetujui menjadi dasar reward."],["04","Reward & payout","Reward creator berasal dari saldo campaign dan tercatat di wallet."]].map(([n,t,d])=><div className="card feature" key={n}><div className="feature-icon">{n}</div><h3>{t}</h3><p className="muted">{d}</p></div>)}</div></section>
  <footer className="wrap footer">© {new Date().getFullYear()} Clipping Creator · Creator & Brand campaign platform</footer>
 </main>
}